---
- name: Playbook that runs a Bash script
  hosts: localhost

  tasks:
  - name: Copy script to target hosts and execute it
    script: ~/ans/scripts/trek.sh
    args:
      executable: /bin/bash
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines

